### ISSUE TITLE
Mcclintock stuck on "prepping read" or "reference fasta created"

### ISSUE THREAD

**Issue by dgodin19** [bergmanlab/mcclintock#101] opened 2022-11-05 03:41 UTC
Hi, 

I am running Mcclintock on a server, and it seems to get stuck on "prepping reads" or "reference fasta created". I tried checking the logs, but there does not seem to be any obvious error, and the bash script does not return an error either. 

Any ideas on how to resolve the issue? 

Thanks in advance.

**Comment by cbergman** [comment] 2022-11-07 14:49
Hi @dgodin19. Has this issue been resolved by letting the process run longer? If not, can you please post more information about how you invoked McClintock at the command line, the size of your your reference genome, read dataset and TE library. Thanks, Casey

**Comment by cbergman** [comment] 2022-11-10 01:26
Hi @dgodin19 

This is unusual and unlike anything we've seen on our systems. We have run the test dataset dozens of times an never experienced a multi-day run time. I ran the test data again today on a machine with 28 cores and 240 Gb memory and running all 12 components took 3 hrs 46 minutes. The job did not use all of the server's resources:

```
Run Time: 03:46:06
Cores per node: 28
CPU Utilized: 23:28:57
CPU Efficiency: 22.26% of 4-09:30:48 core-walltime
Memory Utilized: 11.98 GB
Memory Efficiency: 4.99% of 240.00 GB
```

This job was submitted to a slurm scheduler using the following script:
```
#!/bin/bash
#SBATCH --job-name=mcc_test
#SBATCH --partition=bergman_p
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=28
#SBATCH --mem=240gb
#SBATCH --time=10:00:00
#SBATCH --output=/scratch/username/mcc_test.log
#SBATCH --mail-user=username@uga.edu
#SBATCH --mail-type=END,FAIL

CONDA_BASE=$(conda info --base)
source ${CONDA_BASE}/etc/profile.d/conda.sh
conda activate mcclintock

cd $HOME/github/mcclintock

python3 mcclintock.py \
    -r test/sacCer2.fasta \
    -c test/sac_cer_TE_seqs.fasta \
    -g test/reference_TE_locations.gff \
    -t test/sac_cer_te_families.tsv \
    -1 test/SRR800842_1.fastq.gz \
    -2 test/SRR800842_2.fastq.gz \
    -p 28 \
    -o /scratch/username/mcc_test
```

I suspect the reason your job is taking so long isn't related to McClintock, but may be related to other factors about how you are running your job. I suggest consulting a local HPC expert to get advice on how to run high resource jobs on the server/filesystem you are working on. 

I'll close this issue for now, but feel free to open it if you can provide reproducible code that demonstrates multi-day runtimes for McClintock on the test dataset.

**Closed by cbergman** 2022-11-10 01:26 UTC
